### ISSUE TITLE
Why don't WW problems show up in the donut charts?

### ISSUE THREAD

**Issue by bnmnetp** [RunestoneInteractive/rs#259]

**Comment by bnmnetp** [comment]
![Image](https://github.com/RunestoneInteractive/rs/assets/51115/3d714f10-3c82-4186-a3bd-b60254f8ea36)

Donut charts are now showing up on my development machine.

**Comment by bnmnetp** [comment]
@Tanaquil18 👀

**Comment by Tanaquil18** [comment]
Ooh!  That looks very promising!

I think my 3 highest priorities before MathFest are these donuts (done now?), the progress bars turning green when they should, and fractional points per problem being allowed so that instructors don't have to make each problem worth the same amount as the number of answer blanks.  I see the priority column in the table view, but haven't figured out how I could edit it or select anything in it.

**Comment by bnmnetp** [comment]
Maybe I need to add you to the project.

**Comment by Tanaquil18** [comment]
Yes, that did it!
