### ISSUE TITLE
Error on Generate/Viewl HTML and Save when editing problems on Assignment or Editorial page 

### ISSUE THREAD

**Issue by bhoffman0** [RunestoneInteractive/rs#313]
When I try to edit a question on the Assignments page (https://runestone.academy/runestone/admin/assignments) or the Editorial page (https://runestone.academy/runestone/admin/manage_exercises) and click on the Generate/View HTML button, I get the following error message:
 <img width="568" alt="image" src="https://github.com/RunestoneInteractive/rs/assets/4571962/cd868592-de7e-4c50-9de5-a73811637366">
When I click on Save, it says it saved, but then shows the same error message instead of the fixed problem.

**Comment by bnmnetp** [comment]
Rats!!   .gitignore files strike again.

I had tested the preview stuff on my local machine, but because I had copied things into the new repo from the old repo, I got things that were in the .gitignore file.  But when I added and committed them a few things were accidentally ignored that should not have been, including the scaffolding for doing the preview builds.

Its easy enough to restore those files to fix this problem.

**Comment by bnmnetp** [comment]
Fixed on dev.  Will push live this weekend.

**Comment by bhoffman0** [comment]
Thanks!

**Comment by bnmnetp** [comment]
I think it just does not remove it from the dropdown list. -- that is a bug.  But completely unrelated, and its probably been there for a long time.

**Comment by bhoffman0** [comment]
Sorry I keep adding to the same issue. There's also a problem with displaying Parsons problems and Drag and Drop problems in  assignments in all rst books. I think the https://runestone.academy/runestone/assignments/doAssignment page is missing parsons.css and whatever is needed for dragndrop. They work fine in context. 
<img width="515" alt="image" src="https://github.com/RunestoneInteractive/rs/assets/4571962/04509f80-fcd0-4ee3-8c4a-d09cedf92752">

**Comment by bnmnetp** [comment]
All of these are fixed and live.
