### ISSUE TITLE
Won't show python-swap2 in my list of ebooks

### ISSUE THREAD

**Issue by barbarer** [RunestoneInteractive/rs#377]
I can enroll in the course python-swap2, but it doesn't show in my list of courses.  I have lots of courses in that list.

**Comment by bnmnetp** [comment]
I had made a too quick change to support the new `is_supporter` flag.  (ie don't show the donation ask page and don't show requests for donations to courses that have sent us $$)  It was causing the redirect to the book to happen before we recorded your more permanent status as having added that course to your list of enrolled courses.

Should be fixed in the morning.

**Comment by barbarer** [comment]
Thanks for fixing it!

Dr. Barbara Ericson
Assistant Professor, School of Information
University of Michigan
