### ISSUE TITLE
2.6 practice problems not checking work

### ISSUE THREAD

**Issue by dianenead** [RunestoneInteractive/rs#544]
**Please check the current issues** 2.6 practice problems don't seem to be working to check answers

**What Course are you in**
Discrete_Lewis_FA24_Nead taken from 4th edition open discrete

**What Page were you on**
section 2.6

**What is your username**
mnead (instructor)

**Describe the bug**
2.6 practice problems in text do not seem to be working (when you activate and check answer it does not tell you if you are right or wrong) and when I checked a student's work it seems to give credit for wrong answer, or I am tired and getting it wrong???  For example below a is older than b is not symmetric but that is marked as the correct answer. In the problem below it nothing checked is given as the correct response but symmetric should work and reflexive.

![Screen Shot 2024-10-01 at 8 31 42 PM](https://github.com/user-attachments/assets/4d548a99-6c1e-4816-9210-6c5511b4dda2)

In this one I don't believe it is antisymmetric as a - a is not >=4, other problems in this section we are having a hard time getting correct - 
![Screen Shot 2024-10-01 at 8 36 00 PM](https://github.com/user-attachments/assets/4b1274c6-8f14-4a95-a62f-edbde0259763)

**Comment by bnmnetp** [comment]
@oscarlevin any thoughts?

**Comment by oscarlevin** [comment]
The reading question is correct, but admittedly tricky: if it is never the case that a ~ b and b~ a, then it is also true that *if* a ~ b and b ~ c, *then* a = b.  I've added some feedback to that question that should help clarify this.

The practice problems are are definitely finicky.  They are on my list to recode, but that will take a little while.  I think what is happening is that these WeBWorK questions are set to not provide feedback.  Somehow though, and maybe only some times, if a student enters the correct answer for one part, and then changes that while then getting the correct answer for another part, all the parts were at one time correct, so it is marked as right.  The correct fix is to redo the questions from scratch I think, since they are not providing any feedback at all outside of runestone.

@bnmnetp, could you transfer this issue to github.com/oscarlevin/discrete-book please?

**Comment by bnmnetp** [comment]
@oscarlevin I don't have that option for your repo under the transfer issue link here.
I can leave it open if you want to create a new one and reference this one.

**Comment by oscarlevin** [comment]
Ah, yes I forgot that you can't transfer between repos with different owners.  I made an issue and referenced this.  Feel free to close here; I'll still see it.

**Comment by bnmnetp** [comment]
Closing here:  See oscarlevin/discrete-book#143
